### ISSUE TITLE
MapLibre canvas does not resize properly when the map container's size changes

### ISSUE THREAD

**Issue by helgee** [geoblocks/ol-maplibre-layer#45]
Hi! Thanks for making this...

When resizing the the browser window everything works as expected but not if the size of the map container changes, e.g., when opening the dev tools.

![screencap](https://user-images.githubusercontent.com/1408922/221154375-9364ff54-a1f7-4ef9-ac38-cc0936ef3431.gif)

**Comment by fredj** [comment]
Thanks for the bug report @helgee, will be fixed with #47

**Comment by fredj** [comment]
fixed nad I've published a new version on npm: https://www.npmjs.com/package/@geoblocks/ol-maplibre-layer/v/0.0.6
