### ISSUE TITLE
Use custom pbf tiles and styles

### ISSUE THREAD

**Issue by dmenneck** [geoblocks/ol-maplibre-layer#49]
Is it possible to use custom pbf vector tiles and styles? We have them located at:
- tiles: /tiles/12/2127/1372.pbf
- styles: /styles/highContrast_campusGIS.json

**Comment by ger-benjamin** [comment]
Hello,

you can set your style url here: https://github.com/geoblocks/ol-maplibre-layer/blob/master/examples/demo.js#L17
But you have to serve this json. Then, with MapLibre GL, the style contains the tiles urls.

This project is a wrapper to use MapLibre GL Map together with an OL Map. For more info about how to get a MapLibre GL map, see https://github.com/maplibre/maplibre-gl-js
